// pangea-ring0-OS/src/main.rs
#![no_std]
#![no_main]
#![feature(asm_const)]
#![feature(naked_functions)]
#![feature(panic_info_message)]

extern crate limine; // Use Limine protocol definitions
use core::arch::naked_asm;
use core::fmt::Write;
use core::panic::PanicInfo;

// ============================================================
// 1. Bare-Metal Initialization: Entry Point
// ============================================================

/// In the Rust execution model, we must first set up the stack pointer,
/// then jump to the _start symbol generated by the linker.
#[no_mangle]
pub extern "C" fn _start() -> ! {
    // Initialization to retrieve the memory map and command line passed by the Limine bootloader.
    // The critical part here is to prepare a minimal C ABI-like environment (stack allocation)
    // before the Rust init function executes.

    let limine_responses: u64;
    unsafe {
        asm!(
            "mov {}, [rsi]",       // Limine passes the pointer to the response in rsi
             out(reg) limine_responses
        );
    }

    // Finally, transition to safe Rust code (the main function) here.
    // In PangeaOS, we perform memory mapping integrity checks here.
    pangea::kernel::init(limine_responses);

    unreachable!()
}

// ============================================================
// 2. Main Kernel Logic
// ============================================================

pub mod kernel {
    use core::fmt::{self, Write};
    use limine::common::config;

    // Simple structure for console output (to be replaced by a UART driver later)
    pub struct SerialOut;

    impl Write for SerialOut {
        fn write_str(&mut self, s: &str) -> fmt::Result {
            for byte in s.bytes() {
                // Normally this would be a write to the UART port (0x3F8),
                // but during development it is redirected to QEMU's standard output (stdio).
                // In a Limine-based setup, bios output is also valid.
                unsafe {
                    // Simplified serial port output for x86_64 (development debugging)
                    core::arch::asm!("out dx, al", in("dx") 0x3F8, in("al") byte);
                }
            }
            Ok(())
        }
    }

    pub fn init(limine_responses_ptr: u64) -> ! {
        // The process of zero-clearing the BSS section based on the linker script is
        // typically Rust's libstart_init that runs before main,
        // but for bare-metal we must ensure it manually if not relying on standard start.
        // However, modern rustc (with -Z link-native-libraries=no) handles .bss zeroing
        // in the crt0 assembly provided by the linker script or libcore.

        let mut console = SerialOut;

        // Pangea-ring0-OS boot message
        write!(console, "Pangea-ring0-OS v0.0.1 Booting...\n").unwrap();
        write!(console, "Architecture: Single Address Space (Ring 0)\n").unwrap();
        write!(console, "Trust Anchor: Rust Type System\n").unwrap();

        // Check Limine responses (safe retrieval)
        if limine_responses_ptr == 0 {
            panic!("Limine responses not received!");
        }

        // Perform hardware initialization here (IDT, GDT, strictly no paging)
        unsafe {
            initialize_idt();
            initialize_gdt();
        }

        write!(console, "Environment Initialized.\n").unwrap();

        // Enter the main kernel loop from here
        loop {
            // Enter wait-for-interrupt state (HALT
